/* tslint:disable */
/* eslint-disable */
/**
 * My Site
 * My site description
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MetaVersionGet200Response
 */
export interface MetaVersionGet200Response {
    /**
     * 
     * @type {string}
     * @memberof MetaVersionGet200Response
     */
    'version': string;
}

